global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Analytics Fetcher Service
  - job_name: 'analytics-fetcher'
    static_configs:
      - targets: ['analytics-fetcher:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Database (if you want to monitor PostgreSQL)
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    # Note: You'll need to install postgres_exporter for this to work
    # metrics_path: '/metrics'
    # scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 